spring:
  application:
    name: server-ha
---
server:
  port: 8761
eureka:
  client:
    service-url:
      defaultZone: http://peer2:8762/eureka,http://peer3:8763/eureka
  instance:
    hostname: peer1
spring:
  profiles: peer1

---
server:
  port: 8762
eureka:
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka,http://peer3:8763/eureka
  instance:
    hostname: peer2
spring:
  profiles: peer2
---
  server:
    port: 8763
  eureka:
    client:
      service-url:
        defaultZone: http://peer1:8761/eureka,http://peer2:8762/eureka
    instance:
      hostname: peer3
  spring:
    profiles: peer3




