server:
  port: 9082
spring:
  application:
    name: hystrix-client
eureka:
  instance:
    prefer-ip-address: true
    home-page-url-path: /ribbon
  client:
    service-url:
      defaultZone: http://user:password123@localhost:8761/eureka
    healthcheck:
      enabled: true

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 5000




