server:
  port: 9999
eureka:
  instance:
    prefer-ip-address: true
#    ip-address: 192.168.1.104
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
  client:
    healthcheck:
        enabled: true
    service-url:
      defaultZone: http://user:password123@localhost:8761/eureka
feign:
  hystrix:
    enabled: true

logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    com.spring.could.client1: debug
spring:
  application:
    name: feign-client
